// <auto-generated />
namespace OhKalkulator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedRelationshipBetweenUserAndDnevnikPrehranjevanja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRelationshipBetweenUserAndDnevnikPrehranjevanja));
        
        string IMigrationMetadata.Id
        {
            get { return "201608251837102_AddedRelationshipBetweenUserAndDnevnikPrehranjevanja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
